package runner

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/nnstd/gun/compiler"
	tcontext "github.com/nnstd/gun/compiler/context"
	"github.com/nnstd/gun/compiler/runner"
	"github.com/nnstd/gun/test262/parser"
)

// batchItem represents a single test within a batch.
type batchItem struct {
	Name       string
	FilePath   string
	Source     []byte
	Info       *parser.TestInfo
	IsNegative bool
}

// runBatch compiles a batch of tests into a single binary and executes each one.
func (r *Runner) runBatch(tests []batchItem) []TestResult {
	if len(tests) == 0 {
		return nil
	}

	// Create temp directory for this batch
	tmpDir, err := os.MkdirTemp("", "gun-test262-*")
	if err != nil {
		return makeErrorResults(tests, "create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Write harness.go
	if err := os.WriteFile(filepath.Join(tmpDir, "harness.go"), []byte(HarnessSource()), 0644); err != nil {
		return makeErrorResults(tests, "write harness: %v", err)
	}

	// Create augmented context with test262 globals (shared across all tests in batch)
	ctx := compiler.NewDefaultContext()
	compiler.RegisterTest262Globals(ctx)

	// Track which test indices failed to transpile
	transpileErrors := make(map[int]string)

	// Transpile each test and build the dispatcher main.go
	var mainBuf bytes.Buffer
	mainBuf.WriteString("// Code generated by gun test262 runner. DO NOT EDIT.\n")
	mainBuf.WriteString("package main\n\n")

	// Keep ordered list of test names and their Go functions for the dispatcher
	type testEntry struct {
		Name     string
		FuncName string
	}
	var entries []testEntry

	for i, t := range tests {
		body := parser.StripFrontmatter(t.Source)

		goSource, err := r.transpileTest(body, ctx, t.Name)
		if err != nil {
			transpileErrors[i] = err.Error()
			continue
		}

		funcName := sanitizeTestName(t.Name)
		mainBuf.WriteString(fmt.Sprintf("func %s() {\n%s\n}\n\n", funcName, goSource))
		entries = append(entries, testEntry{Name: t.Name, FuncName: funcName})
	}

	// Write dispatcher main function
	mainBuf.WriteString("func main() {\n")
	mainBuf.WriteString("if len(os.Args) < 2 {\n")
	mainBuf.WriteString("fmt.Fprintf(os.Stderr, \"usage: %s <test_name>\\n\", os.Args[0])\n")
	mainBuf.WriteString("os.Exit(1)\n")
	mainBuf.WriteString("}\n")
	mainBuf.WriteString("switch os.Args[1] {\n")
	for _, e := range entries {
		mainBuf.WriteString(fmt.Sprintf("case %q:\n%s()\n", e.Name, e.FuncName))
	}
	mainBuf.WriteString("default:\n")
	mainBuf.WriteString("fmt.Fprintf(os.Stderr, \"unknown test: %s\\n\", os.Args[1])\n")
	mainBuf.WriteString("os.Exit(1)\n")
	mainBuf.WriteString("}\n")
	mainBuf.WriteString("}\n")

	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), mainBuf.Bytes(), 0644); err != nil {
		return makeErrorResults(tests, "write main.go: %v", err)
	}

	// Scaffold go.mod
	if err := runner.ScaffoldGoMod(tmpDir, r.Verbose); err != nil {
		return makeErrorResults(tests, "scaffold go.mod: %v", err)
	}

	// Build the binary
	binPath := filepath.Join(tmpDir, "test262batch")
	if err := runner.GoBuild(tmpDir, binPath, r.Verbose); err != nil {
		return makeErrorResults(tests, "build: %v", err)
	}

	// Execute each test and collect results
	results := make([]TestResult, 0, len(tests))
	for i, t := range tests {
		if errMsg, ok := transpileErrors[i]; ok {
			results = append(results, TestResult{
				File:   t.FilePath,
				Status: StatusError,
				Error:  errMsg,
			})
			continue
		}

		result := r.executeTest(binPath, t)
		results = append(results, result)
	}

	return results
}

// runSingleTest runs a single test (not batched) for RunSingle.
func (r *Runner) runSingleTest(item batchItem) TestResult {
	results := r.runBatch([]batchItem{item})
	if len(results) > 0 {
		return results[0]
	}
	return TestResult{
		File:   item.FilePath,
		Status: StatusError,
		Error:  "no result from batch execution",
	}
}

// transpileTest transpiles a test body (stripped of frontmatter) to Go source
// using the provided augmented context.
func (r *Runner) transpileTest(body []byte, ctx *tcontext.TranspilerContext, testName string) (string, error) {
	goBytes, err := compiler.CompileWithContext(body, "main", "", false, r.OptLevel, ctx)
	if err != nil {
		return "", fmt.Errorf("transpile %s: %w", testName, err)
	}
	return string(goBytes), nil
}

// executeTest runs a single test binary and classifies the result.
func (r *Runner) executeTest(binPath string, item batchItem) TestResult {
	execCtx, cancel := context.WithTimeout(context.Background(), r.Timeout)
	defer cancel()

	start := time.Now()
	cmd := exec.CommandContext(execCtx, binPath, item.Name)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	duration := time.Since(start).Milliseconds()

	if execCtx.Err() == context.DeadlineExceeded {
		return TestResult{
			File:       item.FilePath,
			Status:     StatusFail,
			DurationMs: duration,
			Error:      fmt.Sprintf("timeout after %v", r.Timeout),
		}
	}

	exitCode := 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			return TestResult{
				File:       item.FilePath,
				Status:     StatusError,
				DurationMs: duration,
				Error:      fmt.Sprintf("exec error: %v", err),
			}
		}
	}

	// Classify result based on exit code
	switch exitCode {
	case 0:
		if item.IsNegative {
			return TestResult{
				File:       item.FilePath,
				Status:     StatusFail,
				DurationMs: duration,
				Error:      fmt.Sprintf("negative test should have thrown %s but exited cleanly", item.Info.Negative.Type),
			}
		}
		return TestResult{
			File:       item.FilePath,
			Status:     StatusPass,
			DurationMs: duration,
		}
	case 42:
		return TestResult{
			File:       item.FilePath,
			Status:     StatusPass,
			DurationMs: duration,
		}
	case 43:
		return TestResult{
			File:       item.FilePath,
			Status:     StatusFail,
			DurationMs: duration,
			Error:      strings.TrimSpace(stderr.String()),
		}
	default:
		stderrStr := strings.TrimSpace(stderr.String())
		if item.IsNegative {
			if strings.Contains(stderrStr, item.Info.Negative.Type) {
				return TestResult{
					File:       item.FilePath,
					Status:     StatusPass,
					DurationMs: duration,
				}
			}
			return TestResult{
				File:       item.FilePath,
				Status:     StatusFail,
				DurationMs: duration,
				Error:      fmt.Sprintf("negative test: expected %s, got: %s", item.Info.Negative.Type, stderrStr),
			}
		}
		return TestResult{
			File:       item.FilePath,
			Status:     StatusFail,
			DurationMs: duration,
			Error:      stderrStr,
		}
	}
}

// makeErrorResults creates error results for all tests in a batch.
func makeErrorResults(tests []batchItem, format string, args ...interface{}) []TestResult {
	msg := fmt.Sprintf(format, args...)
	results := make([]TestResult, len(tests))
	for i, t := range tests {
		results[i] = TestResult{
			File:   t.FilePath,
			Status: StatusError,
			Error:  msg,
		}
	}
	return results
}
