package jsvalue

import (
	"fmt"
)

// NewObject creates an empty object JSValue.
func NewObject() *JSValue {
	return &JSValue{
		typ:       TypeObject,
		prototype: ObjectPrototype,
	}
}

func NewObjectWithPrototype(proto *JSValue) *JSValue {
	return &JSValue{typ: TypeObject, prototype: proto}
}

func NewObjectWithPrototypeAndProps(proto *JSValue, pairs ...any) *JSValue {
	obj := NewObjectWithPrototype(proto)
	if len(pairs) == 0 {
		return obj
	}
	var props *SmallPropMap
	setDataProperty := func(key string, val *JSValue) {
		if val == nil {
			val = NewUndefined()
		}
		if props == nil {
			props = obj.propertiesOrZero()
		}
		props.Set(key, newWritableEnumerableDataDescriptor(val))
	}
	// Handle map argument (generated by transpiler's Go map literal)
	if len(pairs) == 1 {
		if m, ok := pairs[0].(map[string]any); ok {
			for key, val := range m {
				if jsv, ok := val.(*JSValue); ok {
					setDataProperty(key, jsv)
				} else {
					setDataProperty(key, From(val))
				}
			}
			return obj
		}
	}
	for i := 0; i+1 < len(pairs); i += 2 {
		key, _ := pairs[i].(string)
		val, _ := pairs[i+1].(*JSValue)
		setDataProperty(key, val)
	}
	return obj
}

// ObjectFrom creates an object from alternating key (string) and value (*JSValue) pairs.
func ObjectFrom(pairs ...any) *JSValue {
	return NewObjectWithPrototypeAndProps(ObjectPrototype, pairs...)
}

// Keys returns the keys of an object as a JSValue array.
// Implements Object.keys() semantics.
func Keys(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	if obj.isPrimitiveValue() {
		obj = boxedPrimitiveOf(obj)
	}
	keys := obj.EnumerableOwnKeys()
	result := make([]*JSValue, len(keys))
	for i, key := range keys {
		result[i] = NewString(key)
	}
	return NewArray(result...)
}

// Values returns the values of an object as a JSValue array.
// Implements Object.values() semantics.
func Values(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	if obj.isPrimitiveValue() {
		obj = boxedPrimitiveOf(obj)
	}
	props := obj.propertiesOrNil()
	if props == nil {
		return NewArray()
	}
	obj.rlock()
	descs := make([]PropertyDescriptor, 0, props.Len())
	props.ForEach(func(key string, desc *PropertyDescriptor) {
		if desc == nil || !desc.Enumerable {
			return
		}
		descs = append(descs, *desc)
	})
	obj.runlock()
	result := make([]*JSValue, 0, len(descs))
	for i := range descs {
		desc := &descs[i]
		if desc.Get != nil {
			result = append(result, desc.Get(obj))
			continue
		}
		result = append(result, desc.Value)
	}
	return NewArray(result...)
}

func enumerableEntryFromDescriptor(obj *JSValue, key string, desc *PropertyDescriptor) *JSValue {
	val := desc.Value
	if desc.Get != nil {
		val = desc.Get(obj)
	}
	return NewArray(NewString(key), val)
}

// OwnPropertyNames returns all own property names, including non-enumerable ones.
func OwnPropertyNames(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	if obj.isPrimitiveValue() {
		obj = boxedPrimitiveOf(obj)
	}
	keys := obj.OwnKeys()
	result := make([]*JSValue, len(keys))
	for i, key := range keys {
		result[i] = NewString(key)
	}
	return NewArray(result...)
}

// Entries returns the [key, value] pairs of an object as a JSValue array.
// Implements Object.entries() semantics.
func Entries(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	if obj.isPrimitiveValue() {
		obj = boxedPrimitiveOf(obj)
	}
	props := obj.propertiesOrNil()
	if props == nil {
		return NewArray()
	}
	obj.rlock()
	type entryDesc struct {
		key  string
		desc PropertyDescriptor
	}
	descs := make([]entryDesc, 0, props.Len())
	props.ForEach(func(key string, desc *PropertyDescriptor) {
		if desc != nil && desc.Enumerable {
			descs = append(descs, entryDesc{key: key, desc: *desc})
		}
	})
	obj.runlock()
	result := make([]*JSValue, 0, len(descs))
	for i := range descs {
		result = append(result, enumerableEntryFromDescriptor(obj, descs[i].key, &descs[i].desc))
	}
	return NewArray(result...)
}

// FromEntries builds an object from an iterable/array of [key, value] pairs.
func FromEntries(entries *JSValue) *JSValue {
	obj := NewObject()
	if entries == nil {
		return obj
	}
	for i, pair := range entries.Array() {
		if pair == nil {
			continue
		}
		key := pair.Index(0)
		if key == nil || key.TypeString() == "undefined" {
			_ = i
			continue
		}
		obj.Set(PropertyKey(key), pair.Index(1))
	}
	return obj
}

// Assign copies own properties from sources to target.
// Implements Object.assign() semantics.
func Assign(target any, sources ...any) *JSValue {
	t := toJSValue(target)
	if t != nil && t.isPrimitiveValue() {
		t = boxedPrimitiveOf(t)
	}
	for _, src := range sources {
		s := toJSValue(src)
		if s == nil {
			continue
		}
		if s.isPrimitiveValue() {
			s = boxedPrimitiveOf(s)
		}
		for _, key := range s.OwnKeys() {
			t.Set(key, s.Get(key))
		}
	}
	return t
}

func toJSValue(v any) *JSValue {
	if v == nil {
		return NewObject()
	}
	if jv, ok := v.(*JSValue); ok {
		return jv
	}
	return From(v)
}

// Create creates a new object with the specified prototype.
// Implements Object.create() semantics.
func Create(proto *JSValue) *JSValue {
	if proto == nil {
		return NewObject()
	}
	return NewObjectWithPrototype(proto)
}

// DefineProperty defines a property on an object from a descriptor.
// Implements a simplified Object.defineProperty() semantics.
func DefineProperty(obj any, prop any, desc any) *JSValue {
	o := toJSValue(obj)
	d := toJSValue(desc)
	p := fmt.Sprint(prop)
	if d == nil {
		return o
	}

	pd := &PropertyDescriptor{
		Writable:     d.Get("writable").Bool(),
		Enumerable:   d.Get("enumerable").Bool(),
		Configurable: d.Get("configurable").Bool(),
	}

	// Accessor descriptor: get/set
	getter := d.Get("get")
	setter := d.Get("set")
	if getter != nil && getter.funcVal != nil {
		fn := getter
		pd.Get = func(this *JSValue) *JSValue {
			return fn.Call(this)
		}
	}
	if setter != nil && setter.funcVal != nil {
		fn := setter
		pd.Set = func(this *JSValue, val *JSValue) {
			fn.Call(this, val)
		}
	}

	// Data descriptor: value
	val := d.Get("value")
	if val != nil && val.typ != TypeUndefined {
		pd.Value = val
	}

	o.DefineProperty(p, pd)
	return o
}

// DefineAccessor defines or updates an accessor property while preserving the
// existing getter/setter counterpart if only one side is provided.
func DefineAccessor(obj any, prop any, getter, setter *JSValue) *JSValue {
	o := toJSValue(obj)
	p := fmt.Sprint(prop)

	desc := &PropertyDescriptor{
		Enumerable:   true,
		Configurable: true,
	}
	if existing := o.GetOwnProperty(p); existing != nil {
		desc = &PropertyDescriptor{
			Value:        existing.Value,
			Writable:     existing.Writable,
			Enumerable:   existing.Enumerable,
			Configurable: existing.Configurable,
			Get:          existing.Get,
			Set:          existing.Set,
		}
	}
	if getter != nil && getter.funcVal != nil {
		fn := getter
		desc.Get = func(this *JSValue) *JSValue {
			return fn.Call(this)
		}
	}
	if setter != nil && setter.funcVal != nil {
		fn := setter
		desc.Set = func(this *JSValue, val *JSValue) {
			fn.Call(this, val)
		}
	}
	o.DefineProperty(p, desc)
	return o
}

// DefineProperties defines multiple properties on an object at once.
// props is an object where each key maps to a property descriptor.
func DefineProperties(obj any, props any) *JSValue {
	o := toJSValue(obj)
	p := toJSValue(props)
	if p == nil {
		return o
	}
	for _, key := range p.OwnKeys() {
		DefineProperty(o, key, p.Get(key))
	}
	return o
}

// ShallowClone creates a new object with the same own properties as v.
// The clone gets a fresh property map and its own mutex, so concurrent
// mutations to the clone do not affect the original. Prototype chain
// is preserved. Property descriptors are value-copied (not pointer-aliased)
// so in-place Set() on the clone's descriptors won't mutate the original.
// If the original is marked shared, the clone inherits the shared flag so
// that Get() on the clone also returns shallow clones of property values
// (which still alias the original's children).
func (v *JSValue) ShallowClone() *JSValue {
	if v == nil {
		return NewObject()
	}
	// Primitives are immutable — return as-is
	if v.typ != TypeObject && v.typ != TypeFunction {
		return v
	}
	v.rlock()
	defer v.runlock()
	clone := NewObjectWithPrototype(v.prototype)
	// Clone is NOT marked shared — it's private to one goroutine.
	// Its property Values may alias the original's, but the clone's
	// own property map is independent.
	if v.isArr {
		clone.isArr = true
		if arr := v.arrayListOrNil(); arr != nil {
			dst := clone.arrayListOrZero()
			for i := 0; i < arr.Len(); i++ {
				dst.Push(arr.Get(i))
			}
		}
	}
	if props := v.propertiesOrNil(); props != nil {
		dst := clone.propertiesOrZero()
		props.ForEach(func(k string, desc *PropertyDescriptor) {
			if desc == nil {
				return
			}
			// Value-copy the descriptor so Set() on the clone
			// does not mutate the original's desc via in-place
			// desc.Value = value (property.go:229).
			cp := *desc
			dst.Set(k, &cp)
		})
	}
	return clone
}

// NewClass creates a JS class: a constructor function with a prototype object.
// The constructor's "prototype" property holds the prototype that instances inherit from.
// parent is the parent class (or nil for no inheritance).
func NewClass(constructor func(this *JSValue, args ...*JSValue) *JSValue, parent *JSValue) *JSValue {
	var proto *JSValue
	if parent != nil {
		parentProto := parent.Get("prototype")
		if parentProto != nil && parentProto.typ != TypeUndefined {
			proto = NewObjectWithPrototype(parentProto)
		} else {
			proto = NewObject()
		}
	} else {
		proto = NewObject()
	}

	ctor := NewFunction(func(args ...*JSValue) *JSValue {
		// new Class(args): create instance with prototype chain
		instance := NewObjectWithPrototype(proto)
		result := constructor(instance, args...)
		// If constructor explicitly returns an object, use it; otherwise use instance
		if result != nil && result.typ == TypeObject {
			return result
		}
		return instance
	})

	// Store the raw constructor for super() calls via CallSuper
	ctor.setClassInitializer(constructor)

	// Set up Class.prototype and Class.prototype.constructor
	ctor.Set("prototype", proto)
	proto.Set("constructor", ctor)

	// Inherit static methods from parent
	if parent != nil {
		ctor.SetPrototype(parent)
	}

	return ctor
}
