package jsvalue

import "fmt"

// NewObject creates an empty object JSValue.
func NewObject() *JSValue {
	return &JSValue{
		typ:        TypeObject,
		properties: make(map[string]*PropertyDescriptor),
		prototype:  ObjectPrototype,
	}
}

// ObjectFrom creates an object from alternating key (string) and value (*JSValue) pairs.
func ObjectFrom(pairs ...any) *JSValue {
	obj := NewObject()
	// Handle map argument (generated by transpiler's Go map literal)
	if len(pairs) == 1 {
		if m, ok := pairs[0].(map[string]interface{}); ok {
			for key, val := range m {
				if jsv, ok := val.(*JSValue); ok {
					obj.Set(key, jsv)
				} else {
					obj.Set(key, From(val))
				}
			}
			return obj
		}
	}
	// Flat key-value pairs: key1, val1, key2, val2, ...
	for i := 0; i+1 < len(pairs); i += 2 {
		key, _ := pairs[i].(string)
		val, _ := pairs[i+1].(*JSValue)
		if val == nil {
			val = NewUndefined()
		}
		obj.Set(key, val)
	}
	return obj
}

// Keys returns the keys of an object as a JSValue array.
// Implements Object.keys() semantics.
func Keys(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	keys := obj.OwnKeys()
	result := make([]*JSValue, len(keys))
	for i, key := range keys {
		result[i] = NewString(key)
	}
	return NewArray(result...)
}

// Values returns the values of an object as a JSValue array.
// Implements Object.values() semantics.
func Values(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	keys := obj.OwnKeys()
	result := make([]*JSValue, 0, len(keys))
	for _, key := range keys {
		result = append(result, obj.Get(key))
	}
	return NewArray(result...)
}

// Entries returns the [key, value] pairs of an object as a JSValue array.
// Implements Object.entries() semantics.
func Entries(obj *JSValue) *JSValue {
	if obj == nil {
		return NewArray()
	}
	keys := obj.OwnKeys()
	result := make([]*JSValue, 0, len(keys))
	for _, key := range keys {
		result = append(result, NewArray(NewString(key), obj.Get(key)))
	}
	return NewArray(result...)
}

// Assign copies own properties from sources to target.
// Implements Object.assign() semantics.
func Assign(target any, sources ...any) *JSValue {
	t := toJSValue(target)
	for _, src := range sources {
		s := toJSValue(src)
		if s == nil {
			continue
		}
		for _, key := range s.OwnKeys() {
			t.Set(key, s.Get(key))
		}
	}
	return t
}

func toJSValue(v any) *JSValue {
	if v == nil {
		return NewObject()
	}
	if jv, ok := v.(*JSValue); ok {
		return jv
	}
	return From(v)
}

// Create creates a new object with the specified prototype.
// Implements Object.create() semantics.
func Create(proto *JSValue) *JSValue {
	obj := NewObject()
	if proto != nil {
		obj.SetPrototype(proto)
	}
	return obj
}

// DefineProperty defines a property on an object from a descriptor.
// Implements a simplified Object.defineProperty() semantics.
func DefineProperty(obj any, prop any, desc any) *JSValue {
	o := toJSValue(obj)
	d := toJSValue(desc)
	p := fmt.Sprint(prop)
	if d == nil {
		return o
	}

	pd := &PropertyDescriptor{
		Writable:     d.Get("writable").Bool(),
		Enumerable:   d.Get("enumerable").Bool(),
		Configurable: d.Get("configurable").Bool(),
	}

	// Accessor descriptor: get/set
	getter := d.Get("get")
	setter := d.Get("set")
	if getter != nil && getter.funcVal != nil {
		fn := getter
		pd.Get = func(this *JSValue) *JSValue {
			return fn.Call(this)
		}
	}
	if setter != nil && setter.funcVal != nil {
		fn := setter
		pd.Set = func(val *JSValue) {
			fn.Call(val)
		}
	}

	// Data descriptor: value
	val := d.Get("value")
	if val != nil && val.typ != TypeUndefined {
		pd.Value = val
	}

	o.DefineProperty(p, pd)
	return o
}

// DefineProperties defines multiple properties on an object at once.
// props is an object where each key maps to a property descriptor.
func DefineProperties(obj any, props any) *JSValue {
	o := toJSValue(obj)
	p := toJSValue(props)
	if p == nil {
		return o
	}
	for _, key := range p.OwnKeys() {
		DefineProperty(o, key, p.Get(key))
	}
	return o
}

// NewClass creates a JS class: a constructor function with a prototype object.
// The constructor's "prototype" property holds the prototype that instances inherit from.
// parent is the parent class (or nil for no inheritance).
func NewClass(constructor func(this *JSValue, args ...*JSValue) *JSValue, parent *JSValue) *JSValue {
	proto := NewObject()
	if parent != nil {
		// Inheritance: Child.prototype.__proto__ = Parent.prototype
		parentProto := parent.Get("prototype")
		if parentProto != nil && parentProto.typ != TypeUndefined {
			proto.SetPrototype(parentProto)
		}
	}

	ctor := NewFunction(func(args ...*JSValue) *JSValue {
		// new Class(args): create instance with prototype chain
		instance := NewObject()
		instance.SetPrototype(proto)
		result := constructor(instance, args...)
		// If constructor explicitly returns an object, use it; otherwise use instance
		if result != nil && result.typ == TypeObject {
			return result
		}
		return instance
	})

	// Store the raw constructor for super() calls via CallSuper
	ctor.classInit = constructor

	// Set up Class.prototype and Class.prototype.constructor
	ctor.Set("prototype", proto)
	proto.Set("constructor", ctor)

	// Inherit static methods from parent
	if parent != nil {
		ctor.SetPrototype(parent)
	}

	return ctor
}
